source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IPDecimalNumberPad_Example', :exclusive => true do
  pod "IPDecimalNumberPad", :path => "../"
end

target 'IPDecimalNumberPad_Tests', :exclusive => true do
  pod "IPDecimalNumberPad", :path => "../"

  
end
